-- PayLite initial PostgreSQL schema.
-- This file is the canonical initial migration. Alembic executes this file
-- statement by statement; keep all schema changes visible here.

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_company_code UNIQUE (code)
);

CREATE TABLE city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_city_code UNIQUE (code)
);

CREATE TABLE subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company (id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_subject_company_code UNIQUE (company_id, code),
    CONSTRAINT uq_subject_id_company UNIQUE (id, company_id)
);
CREATE INDEX ix_subject_company_id ON subject (company_id);

CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company (id) ON DELETE RESTRICT,
    parent_id BIGINT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_department_company_code UNIQUE (company_id, code),
    CONSTRAINT uq_department_id_company UNIQUE (id, company_id),
    CONSTRAINT fk_department_parent_company
        FOREIGN KEY (parent_id, company_id)
        REFERENCES department (id, company_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_department_not_self_parent CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE INDEX ix_department_parent_id ON department (parent_id);
CREATE INDEX ix_department_company_id ON department (company_id);

CREATE TABLE subject_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subject_department_subject_company
        FOREIGN KEY (subject_id, company_id)
        REFERENCES subject (id, company_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_subject_department_department_company
        FOREIGN KEY (department_id, company_id)
        REFERENCES department (id, company_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_subject_department UNIQUE (subject_id, department_id),
    CONSTRAINT uq_subject_department_code UNIQUE (subject_id, code)
);
CREATE INDEX ix_subject_department_subject_id ON subject_department (subject_id);
CREATE INDEX ix_subject_department_department_id ON subject_department (department_id);

CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company (id) ON DELETE RESTRICT,
    id_number TEXT NOT NULL,
    employee_no VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    employee_type VARCHAR(50) NOT NULL,
    level_code VARCHAR(30),
    level_number INTEGER,
    formal_status BOOLEAN NOT NULL DEFAULT FALSE,
    probation_status VARCHAR(20) NOT NULL DEFAULT 'not_applicable',
    probation_date DATE,
    hire_date DATE NOT NULL,
    termination_date DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_employee_company_id_number UNIQUE (company_id, id_number),
    CONSTRAINT uq_employee_company_employee_no UNIQUE (company_id, employee_no),
    CONSTRAINT ck_employee_level_number CHECK (level_number IS NULL OR level_number >= 0),
    CONSTRAINT ck_employee_probation_status CHECK (
        probation_status IN ('not_applicable', 'in_probation', 'confirmed')
    )
);
CREATE INDEX ix_employee_company_active ON employee (company_id, active);

CREATE TABLE employee_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee (id) ON DELETE RESTRICT,
    subject_id BIGINT NOT NULL REFERENCES subject (id) ON DELETE RESTRICT,
    subject_department_id BIGINT NOT NULL REFERENCES subject_department (id) ON DELETE RESTRICT,
    position_title VARCHAR(100) NOT NULL,
    level_code VARCHAR(30),
    level_number INTEGER,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_employee_assignment_start UNIQUE (employee_id, effective_from),
    CONSTRAINT ex_employee_assignment_dates EXCLUDE USING gist (
        employee_id WITH =,
        daterange(
            effective_from,
            COALESCE(effective_to, 'infinity'::date),
            '[)'
        ) WITH &&
    ),
    CONSTRAINT ck_employee_assignment_dates CHECK (
        effective_to IS NULL OR effective_to > effective_from
    ),
    CONSTRAINT ck_assignment_level_number CHECK (level_number IS NULL OR level_number >= 0)
);
CREATE INDEX ix_employee_assignment_lookup
    ON employee_assignment (employee_id, effective_from, effective_to);
CREATE INDEX ix_employee_assignment_subject_id ON employee_assignment (subject_id);
CREATE INDEX ix_employee_assignment_subject_department_id
    ON employee_assignment (subject_department_id);

CREATE TABLE employee_salary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee (id) ON DELETE RESTRICT,
    fixed_salary NUMERIC(18, 2) NOT NULL,
    performance_base NUMERIC(18, 2) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    source VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_employee_salary_start UNIQUE (employee_id, effective_from),
    CONSTRAINT ex_employee_salary_dates EXCLUDE USING gist (
        employee_id WITH =,
        daterange(
            effective_from,
            COALESCE(effective_to, 'infinity'::date),
            '[)'
        ) WITH &&
    ),
    CONSTRAINT ck_employee_salary_dates CHECK (
        effective_to IS NULL OR effective_to > effective_from
    ),
    CONSTRAINT ck_employee_salary_fixed_nonnegative CHECK (fixed_salary >= 0),
    CONSTRAINT ck_employee_salary_performance_nonnegative CHECK (performance_base >= 0)
);
CREATE INDEX ix_employee_salary_lookup
    ON employee_salary (employee_id, effective_from, effective_to);

CREATE TABLE employee_bank_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee (id) ON DELETE RESTRICT,
    account_number TEXT NOT NULL,
    account_name VARCHAR(100) NOT NULL,
    bank_name VARCHAR(100),
    branch_name VARCHAR(100),
    is_primary BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_employee_bank_account UNIQUE (employee_id, account_number),
    CONSTRAINT ex_employee_bank_dates EXCLUDE USING gist (
        employee_id WITH =,
        daterange(
            effective_from,
            COALESCE(effective_to, 'infinity'::date),
            '[)'
        ) WITH &&
    ),
    CONSTRAINT ck_employee_bank_dates CHECK (
        effective_to IS NULL OR effective_to > effective_from
    )
);
CREATE INDEX ix_employee_bank_primary ON employee_bank_account (employee_id, is_primary);

CREATE TABLE employee_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employee (id) ON DELETE RESTRICT,
    city_id BIGINT NOT NULL REFERENCES city (id) ON DELETE RESTRICT,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_employee_base_start UNIQUE (employee_id, effective_from),
    CONSTRAINT ex_employee_base_dates EXCLUDE USING gist (
        employee_id WITH =,
        daterange(
            effective_from,
            COALESCE(effective_to, 'infinity'::date),
            '[)'
        ) WITH &&
    ),
    CONSTRAINT ck_employee_base_dates CHECK (
        effective_to IS NULL OR effective_to > effective_from
    )
);
CREATE INDEX ix_employee_base_lookup
    ON employee_base (employee_id, effective_from, effective_to);

CREATE TABLE payroll_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    actual_payment_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payroll_period_start UNIQUE (period_start),
    CONSTRAINT uq_payroll_period_year_month UNIQUE (year, month),
    CONSTRAINT ck_payroll_period_year CHECK (
        year = EXTRACT(YEAR FROM period_start)::integer
    ),
    CONSTRAINT ck_payroll_period_month_match CHECK (
        month = EXTRACT(MONTH FROM period_start)::integer
    ),
    CONSTRAINT ck_payroll_period_first_day CHECK (EXTRACT(DAY FROM period_start) = 1),
    CONSTRAINT ck_payroll_period_last_day CHECK (
        period_end = (
            date_trunc('month', period_start) + INTERVAL '1 month - 1 day'
        )::date
    ),
    CONSTRAINT ck_payroll_period_dates CHECK (period_end >= period_start),
    CONSTRAINT ck_payroll_period_month_range CHECK (month BETWEEN 1 AND 12)
);

CREATE TABLE payroll_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL REFERENCES subject (id) ON DELETE RESTRICT,
    payroll_period_id BIGINT NOT NULL REFERENCES payroll_period (id) ON DELETE RESTRICT,
    batch_type VARCHAR(30) NOT NULL,
    batch_no INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    name VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payroll_batch_identity UNIQUE (
        subject_id, payroll_period_id, batch_type, batch_no
    ),
    CONSTRAINT uq_payroll_batch_id_subject_period UNIQUE (id, subject_id, payroll_period_id),
    CONSTRAINT ck_payroll_batch_type CHECK (
        batch_type IN ('normal', 'supplement', 'performance_supplement', 'other')
    ),
    CONSTRAINT ck_payroll_batch_status CHECK (
        status IN ('draft', 'trial', 'confirmed', 'locked', 'exported', 'cancelled')
    ),
    CONSTRAINT ck_payroll_batch_number_positive CHECK (batch_no > 0)
);
CREATE INDEX ix_payroll_batch_period_status ON payroll_batch (payroll_period_id, status);
CREATE UNIQUE INDEX uq_payroll_batch_normal
    ON payroll_batch (subject_id, payroll_period_id)
    WHERE batch_type = 'normal';

CREATE TABLE import_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_period_id BIGINT REFERENCES payroll_period (id) ON DELETE RESTRICT,
    payroll_batch_id BIGINT REFERENCES payroll_batch (id) ON DELETE RESTRICT,
    import_type VARCHAR(30) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_sha256 VARCHAR(64) NOT NULL,
    template_version VARCHAR(50) NOT NULL,
    field_mapping JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(30) NOT NULL DEFAULT 'uploaded',
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_import_batch_period_type_file UNIQUE (
        payroll_period_id, import_type, file_sha256
    ),
    CONSTRAINT ck_import_batch_type CHECK (
        import_type IN ('employee_master', 'attendance', 'performance')
    ),
    CONSTRAINT ck_import_batch_status CHECK (
        status IN ('uploaded', 'validated', 'partially_imported', 'imported', 'rejected')
    )
);
CREATE INDEX ix_import_batch_period_type ON import_batch (payroll_period_id, import_type);

CREATE TABLE attendance_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id BIGINT NOT NULL REFERENCES import_batch (id) ON DELETE RESTRICT,
    payroll_period_id BIGINT NOT NULL REFERENCES payroll_period (id) ON DELETE RESTRICT,
    employee_id BIGINT NOT NULL REFERENCES employee (id) ON DELETE RESTRICT,
    expected_work_days NUMERIC(8, 2) NOT NULL,
    late_minutes INTEGER NOT NULL DEFAULT 0,
    early_leave_minutes INTEGER NOT NULL DEFAULT 0,
    leave_days NUMERIC(8, 2) NOT NULL DEFAULT 0,
    leave_type VARCHAR(20) NOT NULL DEFAULT 'none',
    missed_punch_count INTEGER NOT NULL DEFAULT 0,
    punch_corrected BOOLEAN NOT NULL DEFAULT FALSE,
    exception_note TEXT,
    raw_values JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attendance_import_employee UNIQUE (import_batch_id, employee_id),
    CONSTRAINT uq_attendance_period_employee UNIQUE (payroll_period_id, employee_id),
    CONSTRAINT ck_attendance_work_days_nonnegative CHECK (expected_work_days >= 0),
    CONSTRAINT ck_attendance_late_nonnegative CHECK (late_minutes >= 0),
    CONSTRAINT ck_attendance_early_nonnegative CHECK (early_leave_minutes >= 0),
    CONSTRAINT ck_attendance_leave_nonnegative CHECK (leave_days >= 0),
    CONSTRAINT ck_attendance_missed_nonnegative CHECK (missed_punch_count >= 0),
    CONSTRAINT ck_attendance_leave_type CHECK (leave_type IN ('none', 'paid', 'unpaid'))
);
CREATE INDEX ix_attendance_period_employee ON attendance_record (payroll_period_id, employee_id);
CREATE INDEX ix_attendance_import_batch_id ON attendance_record (import_batch_id);

CREATE TABLE performance_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id BIGINT NOT NULL REFERENCES import_batch (id) ON DELETE RESTRICT,
    payroll_period_id BIGINT NOT NULL REFERENCES payroll_period (id) ON DELETE RESTRICT,
    employee_id BIGINT NOT NULL REFERENCES employee (id) ON DELETE RESTRICT,
    coefficient NUMERIC(14, 6) NOT NULL,
    source_value VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_performance_import_employee UNIQUE (import_batch_id, employee_id),
    CONSTRAINT uq_performance_period_employee UNIQUE (payroll_period_id, employee_id),
    CONSTRAINT ck_performance_coefficient_nonnegative CHECK (coefficient >= 0)
);
CREATE INDEX ix_performance_period_employee ON performance_record (payroll_period_id, employee_id);
CREATE INDEX ix_performance_import_batch_id ON performance_record (import_batch_id);

CREATE TABLE social_security_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL REFERENCES city (id) ON DELETE RESTRICT,
    effective_from DATE NOT NULL,
    effective_to DATE,
    version VARCHAR(50) NOT NULL,
    source TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_social_security_city_start UNIQUE (city_id, effective_from),
    CONSTRAINT ex_social_security_rule_dates EXCLUDE USING gist (
        city_id WITH =,
        daterange(
            effective_from,
            COALESCE(effective_to, 'infinity'::date),
            '[)'
        ) WITH &&
    ),
    CONSTRAINT ck_social_security_rule_dates CHECK (
        effective_to IS NULL OR effective_to > effective_from
    )
);
CREATE INDEX ix_social_security_rule_lookup
    ON social_security_rule (city_id, effective_from, effective_to);

CREATE TABLE social_security_item_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_security_rule_id BIGINT NOT NULL REFERENCES social_security_rule (id) ON DELETE CASCADE,
    item_code VARCHAR(30) NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    company_rate NUMERIC(12, 8) NOT NULL,
    employee_rate NUMERIC(12, 8) NOT NULL,
    base_min NUMERIC(18, 2) NOT NULL,
    base_max NUMERIC(18, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_social_security_item UNIQUE (social_security_rule_id, item_code),
    CONSTRAINT ck_social_security_rates CHECK (company_rate >= 0 AND employee_rate >= 0),
    CONSTRAINT ck_social_security_bases CHECK (base_min >= 0 AND base_max >= base_min)
);
CREATE INDEX ix_social_security_item_rule_rule_id
    ON social_security_item_rule (social_security_rule_id);

CREATE TABLE housing_fund_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL REFERENCES city (id) ON DELETE RESTRICT,
    effective_from DATE NOT NULL,
    effective_to DATE,
    company_rate NUMERIC(12, 8) NOT NULL,
    employee_rate NUMERIC(12, 8) NOT NULL,
    base_min NUMERIC(18, 2) NOT NULL,
    base_max NUMERIC(18, 2) NOT NULL,
    version VARCHAR(50) NOT NULL,
    source TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_housing_fund_city_start UNIQUE (city_id, effective_from),
    CONSTRAINT ex_housing_fund_rule_dates EXCLUDE USING gist (
        city_id WITH =,
        daterange(
            effective_from,
            COALESCE(effective_to, 'infinity'::date),
            '[)'
        ) WITH &&
    ),
    CONSTRAINT ck_housing_fund_rule_dates CHECK (
        effective_to IS NULL OR effective_to > effective_from
    ),
    CONSTRAINT ck_housing_fund_rates CHECK (company_rate >= 0 AND employee_rate >= 0),
    CONSTRAINT ck_housing_fund_bases CHECK (base_min >= 0 AND base_max >= base_min)
);
CREATE INDEX ix_housing_fund_rule_lookup
    ON housing_fund_rule (city_id, effective_from, effective_to);

CREATE TABLE attendance_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    effective_from DATE NOT NULL,
    effective_to DATE,
    standard_hours NUMERIC(5, 2) NOT NULL DEFAULT 8,
    missed_punch_amount NUMERIC(18, 2) NOT NULL DEFAULT 30,
    exempt_level_number INTEGER NOT NULL DEFAULT 7,
    version VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attendance_rule_start UNIQUE (effective_from),
    CONSTRAINT ex_attendance_rule_dates EXCLUDE USING gist (
        daterange(
            effective_from,
            COALESCE(effective_to, 'infinity'::date),
            '[)'
        ) WITH &&
    ),
    CONSTRAINT ck_attendance_rule_dates CHECK (
        effective_to IS NULL OR effective_to > effective_from
    ),
    CONSTRAINT ck_attendance_standard_hours CHECK (standard_hours > 0),
    CONSTRAINT ck_attendance_missed_punch_amount CHECK (missed_punch_amount >= 0),
    CONSTRAINT ck_attendance_exempt_level CHECK (exempt_level_number >= 0)
);

CREATE TABLE import_row (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id BIGINT NOT NULL REFERENCES import_batch (id) ON DELETE CASCADE,
    sheet_name VARCHAR(255) NOT NULL,
    source_row_number INTEGER NOT NULL,
    validation_status VARCHAR(20) NOT NULL,
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    normalized_data JSONB,
    errors JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_import_row_location UNIQUE (
        import_batch_id, sheet_name, source_row_number
    ),
    CONSTRAINT ck_import_row_status CHECK (
        validation_status IN ('valid', 'invalid', 'corrected', 'imported')
    )
);
CREATE INDEX ix_import_row_batch_status ON import_row (import_batch_id, validation_status);

CREATE TABLE payroll_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_batch_id BIGINT NOT NULL,
    payroll_period_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL REFERENCES employee (id) ON DELETE RESTRICT,
    snapshot_id_number TEXT NOT NULL,
    snapshot_employee_no VARCHAR(50) NOT NULL,
    snapshot_employee_name VARCHAR(100) NOT NULL,
    snapshot_department_name VARCHAR(200),
    snapshot_position_title VARCHAR(100),
    snapshot_level_code VARCHAR(30),
    snapshot_level_number INTEGER,
    snapshot_fixed_salary NUMERIC(18, 2) NOT NULL,
    snapshot_performance_base NUMERIC(18, 2) NOT NULL,
    snapshot_base_city_name VARCHAR(100),
    snapshot_bank_account TEXT,
    gross_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    deduction_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    net_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    employer_cost_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    calculation_status VARCHAR(20) NOT NULL DEFAULT 'trial',
    external_tax_data JSONB,
    external_tax_source TEXT,
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payroll_record_batch_scope
        FOREIGN KEY (payroll_batch_id, subject_id, payroll_period_id)
        REFERENCES payroll_batch (id, subject_id, payroll_period_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_payroll_record_batch_employee UNIQUE (payroll_batch_id, employee_id),
    CONSTRAINT ck_payroll_record_status CHECK (
        calculation_status IN ('trial', 'confirmed', 'locked', 'superseded')
    ),
    CONSTRAINT ck_payroll_record_amounts_nonnegative CHECK (
        gross_amount >= 0
        AND deduction_amount >= 0
        AND net_amount >= 0
        AND employer_cost_amount >= 0
    )
);
CREATE INDEX ix_payroll_record_period_subject
    ON payroll_record (payroll_period_id, subject_id);
CREATE INDEX ix_payroll_record_employee_id ON payroll_record (employee_id);

CREATE TABLE payroll_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_record_id BIGINT NOT NULL REFERENCES payroll_record (id) ON DELETE CASCADE,
    item_code VARCHAR(50) NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    item_category VARCHAR(20) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    quantity NUMERIC(14, 6),
    rate NUMERIC(12, 8),
    source_type VARCHAR(50),
    source_reference TEXT,
    in_social_security_base BOOLEAN NOT NULL DEFAULT FALSE,
    in_housing_fund_base BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payroll_item_code UNIQUE (payroll_record_id, item_code),
    CONSTRAINT ck_payroll_item_category CHECK (
        item_category IN ('income', 'deduction', 'employer_cost', 'external_tax')
    ),
    CONSTRAINT ck_payroll_item_amount_nonnegative CHECK (amount >= 0)
);
CREATE INDEX ix_payroll_item_record_category
    ON payroll_item (payroll_record_id, item_category);

CREATE TABLE payroll_calculation_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_record_id BIGINT NOT NULL REFERENCES payroll_record (id) ON DELETE CASCADE,
    step_code VARCHAR(50) NOT NULL,
    formula_text TEXT NOT NULL,
    inputs JSONB NOT NULL DEFAULT '{}'::jsonb,
    amount NUMERIC(18, 2),
    rule_reference VARCHAR(100),
    source_type VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payroll_calculation_step UNIQUE (payroll_record_id, step_code)
);
CREATE INDEX ix_payroll_calculation_record ON payroll_calculation_detail (payroll_record_id);

CREATE TABLE correction_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_batch_id BIGINT NOT NULL REFERENCES payroll_batch (id) ON DELETE RESTRICT,
    replacement_batch_id BIGINT NOT NULL REFERENCES payroll_batch (id) ON DELETE RESTRICT,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'requested',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_correction_replacement_batch UNIQUE (replacement_batch_id),
    CONSTRAINT ck_correction_distinct_batches CHECK (original_batch_id <> replacement_batch_id),
    CONSTRAINT ck_correction_status CHECK (status IN ('requested', 'applied', 'cancelled'))
);
CREATE INDEX ix_correction_original_batch_id ON correction_batch (original_batch_id);

CREATE TABLE export_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_period_id BIGINT NOT NULL REFERENCES payroll_period (id) ON DELETE RESTRICT,
    payroll_batch_id BIGINT REFERENCES payroll_batch (id) ON DELETE RESTRICT,
    output_type VARCHAR(30) NOT NULL,
    template_version VARCHAR(50) NOT NULL,
    output_path TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'started',
    parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT ck_export_output_type CHECK (
        output_type IN ('labor_cost', 'bank_payment', 'payroll_sheet', 'tax_assistance')
    ),
    CONSTRAINT ck_export_status CHECK (status IN ('started', 'completed', 'failed'))
);
CREATE INDEX ix_export_batch_period_type ON export_batch (payroll_period_id, output_type);
CREATE INDEX ix_export_batch_payroll_batch_id ON export_batch (payroll_batch_id);

CREATE TABLE export_warning (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    export_batch_id BIGINT NOT NULL REFERENCES export_batch (id) ON DELETE CASCADE,
    employee_id BIGINT REFERENCES employee (id) ON DELETE RESTRICT,
    field_name VARCHAR(100),
    code VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_export_warning_severity CHECK (severity IN ('info', 'warning', 'error'))
);
CREATE INDEX ix_export_warning_batch_severity
    ON export_warning (export_batch_id, severity);
CREATE INDEX ix_export_warning_employee_id ON export_warning (employee_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_employee_updated_at
BEFORE UPDATE ON employee
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_payroll_batch_updated_at
BEFORE UPDATE ON payroll_batch
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION prevent_department_cycle()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    has_cycle BOOLEAN;
BEGIN
    IF NEW.parent_id IS NULL THEN
        RETURN NEW;
    END IF;

    WITH RECURSIVE ancestors(id) AS (
        SELECT NEW.parent_id
        UNION ALL
        SELECT department.parent_id
        FROM department
        JOIN ancestors ON department.id = ancestors.id
        WHERE department.company_id = NEW.company_id
          AND department.parent_id IS NOT NULL
    )
    SELECT EXISTS (SELECT 1 FROM ancestors WHERE id = NEW.id) INTO has_cycle;

    IF has_cycle THEN
        RAISE EXCEPTION 'Department hierarchy cannot contain a cycle'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_department_no_cycle
BEFORE INSERT OR UPDATE OF parent_id, company_id ON department
FOR EACH ROW
EXECUTE FUNCTION prevent_department_cycle();

CREATE OR REPLACE FUNCTION prevent_locked_payroll_record_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.calculation_status IN ('locked', 'superseded') THEN
        RAISE EXCEPTION 'Payroll record % is immutable after locking', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_payroll_record_immutable_after_lock
BEFORE UPDATE OR DELETE ON payroll_record
FOR EACH ROW
EXECUTE FUNCTION prevent_locked_payroll_record_mutation();

CREATE OR REPLACE FUNCTION prevent_locked_payroll_child_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    record_id BIGINT;
BEGIN
    record_id := CASE
        WHEN TG_OP = 'DELETE' THEN OLD.payroll_record_id
        ELSE NEW.payroll_record_id
    END;

    IF EXISTS (
        SELECT 1
        FROM payroll_record
        WHERE id = record_id
          AND calculation_status IN ('locked', 'superseded')
    ) THEN
        RAISE EXCEPTION 'Payroll record % is immutable after locking', record_id
            USING ERRCODE = 'restrict_violation';
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_payroll_item_immutable_after_lock
BEFORE INSERT OR UPDATE OR DELETE ON payroll_item
FOR EACH ROW
EXECUTE FUNCTION prevent_locked_payroll_child_mutation();

CREATE TRIGGER trg_payroll_calculation_immutable_after_lock
BEFORE INSERT OR UPDATE OR DELETE ON payroll_calculation_detail
FOR EACH ROW
EXECUTE FUNCTION prevent_locked_payroll_child_mutation();

COMMENT ON TABLE payroll_record IS '工资结果快照；不得仅依赖当前员工档案解释历史金额。';
COMMENT ON TABLE import_batch IS '原始文件级导入追溯记录。';
COMMENT ON TABLE import_row IS '导入文件的工作表、原始行号和逐行校验记录。';
COMMENT ON TABLE correction_batch IS '锁定批次的更正关系。';
COMMENT ON COLUMN employee.id_number IS '身份证号码，按文本保存，保留末位 X。';
COMMENT ON COLUMN payroll_record.external_tax_data IS '外部提供的税务字段；系统不计算个税。';

-- Direct execution bypasses Alembic bookkeeping. After applying this file,
-- run `alembic stamp 0001_initial_schema` from the backend directory before
-- running future Alembic upgrades.
