CREATE TABLE payroll_trial_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_batch_id BIGINT NOT NULL REFERENCES payroll_batch(id) ON DELETE RESTRICT,
    input_fingerprint VARCHAR(64) NOT NULL,
    input_snapshot JSONB NOT NULL,
    results JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
CREATE INDEX ix_payroll_trial_batch_id ON payroll_trial_run (payroll_batch_id, id);
