CREATE TABLE attendance_incentive_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company(id) ON DELETE RESTRICT,
    payroll_period_id BIGINT NOT NULL REFERENCES payroll_period(id) ON DELETE RESTRICT,
    source_period_id BIGINT NOT NULL REFERENCES payroll_period(id) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL,
    input_fingerprint VARCHAR(64) NOT NULL,
    pool_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    allocated_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    average_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    remainder_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    source_snapshot JSONB NOT NULL,
    candidate_snapshot JSONB NOT NULL,
    allocations JSONB NOT NULL,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uq_attendance_incentive_version
        UNIQUE (company_id, payroll_period_id, input_fingerprint),
    CONSTRAINT ck_attendance_incentive_status
        CHECK (status IN ('calculated', 'empty')),
    CONSTRAINT ck_attendance_incentive_pool_nonnegative CHECK (pool_amount >= 0),
    CONSTRAINT ck_attendance_incentive_allocated_nonnegative CHECK (allocated_amount >= 0)
);
CREATE INDEX ix_attendance_incentive_company_period
    ON attendance_incentive_run (company_id, payroll_period_id, id);

ALTER TABLE payroll_trial_run
    ADD COLUMN ordinary_input_fingerprint VARCHAR(64),
    ADD COLUMN incentive_run_id BIGINT,
    ADD COLUMN includes_final_incentive BOOLEAN NOT NULL DEFAULT false;
UPDATE payroll_trial_run SET ordinary_input_fingerprint = input_fingerprint;
ALTER TABLE payroll_trial_run
    ADD CONSTRAINT fk_payroll_trial_incentive_run
    FOREIGN KEY (incentive_run_id) REFERENCES attendance_incentive_run(id) ON DELETE RESTRICT;
