import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, App, Button, Card, Drawer, Form, Input, Popconfirm, Select, Space, Table, Typography } from "antd";
import { useState } from "react";
import { resources, type City, type Department, type Subject, type SubjectDepartment } from "../shared/api/resources";
import styles from "./OrganizationPage.module.css";

type Kind = "city" | "subject" | "department" | "relation";
type Row = City | Subject | Department | SubjectDepartment;

export function OrganizationPage() {
  const { message } = App.useApp(); const qc = useQueryClient(); const [form] = Form.useForm();
  const [kind, setKind] = useState<Kind | null>(null); const [editing, setEditing] = useState<Row | null>(null);
  const company = useQuery({ queryKey: ["org", "company"], queryFn: resources.company });
  const cities = useQuery({ queryKey: ["org", "cities"], queryFn: resources.cities });
  const subjects = useQuery({ queryKey: ["org", "subjects"], queryFn: resources.subjects });
  const departments = useQuery({ queryKey: ["org", "departments"], queryFn: resources.departments });
  const relations = useQuery({ queryKey: ["org", "relations"], queryFn: resources.subjectDepartments });
  const refresh = () => qc.invalidateQueries({ queryKey: ["org"] });
  const mutation = useMutation({ mutationFn: (v: Record<string, unknown>) => { if (kind === "city") return editing ? resources.updateCity(editing.id, v) : resources.createCity(v); if (kind === "subject") return editing ? resources.updateSubject(editing.id, v) : resources.createSubject({ ...v, company_id: company.data!.id }); if (kind === "department") return editing ? resources.updateDepartment(editing.id, v) : resources.createDepartment({ ...v, company_id: company.data!.id }); return editing ? resources.updateSubjectDepartment(editing.id, v) : resources.createSubjectDepartment({ ...v, company_id: company.data!.id }); }, onSuccess: () => { message.success("已保存"); setKind(null); setEditing(null); refresh(); }, onError: e => message.error(e.message) });
  const remove = useMutation({ mutationFn: ({ k, id }: { k: Kind; id: number }) => k === "city" ? resources.deleteCity(id) : k === "subject" ? resources.deleteSubject(id) : k === "department" ? resources.deleteDepartment(id) : resources.deleteSubjectDepartment(id), onSuccess: refresh, onError: e => message.error(e.message) });
  const open = (k: Kind, row?: Row) => { setKind(k); setEditing(row ?? null); form.resetFields(); if (row) form.setFieldsValue(row); };
  const table = (k: Kind, data: Row[], loading: boolean) => <Card title={k === "city" ? "城市" : k === "subject" ? "主体" : k === "department" ? "部门" : "主体部门实例"} extra={<Button type="link" onClick={() => open(k)}>新增</Button>} loading={loading}><Table rowKey="id" size="small" pagination={false} dataSource={data} columns={[{ title: "编码", dataIndex: "code" }, { title: "名称", dataIndex: "name" }, ...(k === "relation" ? [{ title: "主体", dataIndex: "subject_id" }, { title: "部门", dataIndex: "department_id" }] : []), { title: "操作", render: (_: unknown, row: Row) => <Space><Button type="link" onClick={() => open(k, row)}>编辑</Button><Popconfirm title="确认删除？" onConfirm={() => remove.mutate({ k, id: row.id })}><Button type="link" danger>删除</Button></Popconfirm></Space> }]} /></Card>;
  return <div className={styles.page}><Typography.Title>公司与组织</Typography.Title>{company.isError && <Alert type="error" message={company.error.message} />}{!company.data && !company.isLoading ? <CompanyForm onSaved={refresh} /> : null}{company.data ? <Card title="目标公司" extra={<Typography.Text>{company.data.code}</Typography.Text>}><Typography.Text>{company.data.name}</Typography.Text></Card> : null}<Space className={styles.grid} align="start" wrap>{table("city", cities.data ?? [], cities.isLoading)}{table("subject", subjects.data ?? [], subjects.isLoading)}{table("department", departments.data ?? [], departments.isLoading)}{table("relation", relations.data ?? [], relations.isLoading)}</Space><Drawer title={editing ? "编辑资料" : "新增资料"} open={!!kind} onClose={() => setKind(null)} extra={<Button type="primary" onClick={() => form.submit()} loading={mutation.isPending}>保存</Button>}><Form form={form} layout="vertical" onFinish={v => mutation.mutate(v)}><Form.Item name="code" label="编码" rules={[{ required: true }]}><Input disabled={!!editing} /></Form.Item><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item>{kind === "department" && <Form.Item name="parent_id" label="上级部门"><Select allowClear options={(departments.data ?? []).filter(x => x.id !== editing?.id).map(x => ({ label: x.name, value: x.id }))} /></Form.Item>}{kind === "relation" && !editing && <><Form.Item name="subject_id" label="主体" rules={[{ required: true }]}><Select options={(subjects.data ?? []).map(x => ({ label: x.name, value: x.id }))} /></Form.Item><Form.Item name="department_id" label="部门" rules={[{ required: true }]}><Select options={(departments.data ?? []).map(x => ({ label: x.name, value: x.id }))} /></Form.Item></>}</Form></Drawer></div>;
}

function CompanyForm({ onSaved }: { onSaved: () => void }) { const { message } = App.useApp(); const [form] = Form.useForm(); const m = useMutation({ mutationFn: resources.createCompany, onSuccess: onSaved, onError: e => message.error(e.message) }); return <Card title="初始化目标公司" extra={<Button type="primary" onClick={() => form.submit()} loading={m.isPending}>保存</Button>}><Form form={form} layout="inline" onFinish={v => m.mutate(v)}><Form.Item name="code" label="编码" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item></Form></Card>; }
